fix: roll back rustfs version to 1.0.0-alpha.99 due to issue
error: encrypted object metadata is incomplete
https://github.com/rustfs/rustfs/issues/3028